name: Feature Request
description: File a feature request.
title: '[Feature]: '
labels:
  - enhancement
body:
  - type: input
    id: description
    attributes:
      label: Description
      description: Provide a short clear issue description.
      placeholder: Provide a short clear issue description.
      value: Short clear issue description.
    validations:
      required: true
  - type: textarea
    id: todo
    attributes:
      label: Todo
      description: What are the steps needed to complete this feature?
      placeholder: Steps to complete this feature.
      value: |-
        - [ ] Step 1.
        - [ ] Step 2.
        - [ ] ...
    validations:
      required: true
  - type: checkboxes
    id: dod
    attributes:
      label: Definition Of Done
      description: ' Did you complete the issue according to the definition of done?'
      options:
        - label: Did you create a new branch?
          required: false
        - label: ' Did you commit after each major change?'
          required: false
        - label: Did you complete all steps outlined in this issue?
          required: false
        - label: ' Did you make a pull request to merge with the dev branch?'
          required: false
  - type: markdown
    attributes:
      value: >-
        ## Code of Conduct

        By submitting this issue, you agree to follow our [Code of
        Conduct](https://github.com/VantorreWannes/binary-tree-zig/blob/dev/Code-of-Conduct.md). 
  - type: markdown
    attributes:
      value: >-
        This template was generated with [Issue Forms
        Creator](https://issue-forms-creator.netlify.app)
